### ISSUE TITLE
Database with real data  and working application

### ISSUE THREAD

**Issue by micmit** [ProgrammingAspNetMvcBook/CodeExamples#3]
I downloaded zip file from github.  Managed to compile after fixing references with nuget.  However, aspnet-Ebuy.Website-20120930232619.mdf  is only membership database. Where is real data ?  I mean, for the existing github  codebase can we see the search result like on page 169 figure 8-3

**Comment by bluee** [comment]
Hi micmit,
 It seems like authors of the book not caring about this solution and it's half completed.

**Comment by jchadwick** [comment]
Sorry, we are still working on completing this.  It will be done within the next few weeks.

**Comment by Reducer** [comment]
Edit:
If I comment out the InverseProperty attribute for Owner in Auction.cs, the database is created succesfully.
Maybe it's helpful for someone.
...
        public class Metadata
...
        // [InverseProperty("Selling")]
        public object Owner;

Hello jchadwick,
I tried a lot, but couldn't find a way to create the database for the EbuyDataContext.
It would really help a lot, if you could give any advice to the readers of the book for this issue.
I even don't know, if EF should create the database and fails or if I got it all wrong.
Thanks
